// import GlobalProvider from "@/components/application/GlobalProvider";
// import { Toaster } from "@/components/ui/sonner";
import { Assistant } from "next/font/google";
import "./globals.css";
import GlobalProvider from "../components/application/GlobalProvider";
import { Toaster } from "../components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next"
const assistantFont = Assistant({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap'
})
export const metadata = {
  title: "rp-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistantFont.className} antialiased`}
      >
        <GlobalProvider>
          <SpeedInsights />
          <Toaster />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
